In [103]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [104]:
df = pd.read_csv("/workspaces/EDA-on-Netflix-Dataset/datasets/raw/netflix_movies_detailed_up_to_2025.csv")

In [105]:
# Knowing the shape
df.shape

(16000, 18)

In [106]:
# Getting the info about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       16000 non-null  int64
 1   type          16000 non-null  str
 2   title         16000 non-null  str
 3   director      15868 non-null  str
 4   cast          15796 non-null  str
 5   country       15534 non-null  str
 6   date_added    16000 non-null  str
 7   release_year  16000 non-null  int64
 8   rating        16000 non-null  float64
 9   duration      0 non-null      float64
 10  genres        15893 non-null  str
 11  language      16000 non-null  str
 12  description   15868 non-null  str
 13  popularity    16000 non-null  float64
 14  vote_count    16000 non-null  int64
 15  vote_average  16000 non-null  float64
 16  budget        16000 non-null  int64
 17  revenue       16000 non-null  int64
dtypes: float64(4), int64(5), str(9)
memory usage: 2.2 MB

In [107]:
df.describe()

,show_id,release_year,rating,duration,popularity,vote_count,vote_average,budget,revenue
count,1.600000e+04,16000.000000,16000.000000,0.0,16000.000000,16000.000000,16000.000000,1.600000e+04,1.600000e+04
mean,5.266582e+05,2017.500000,5.956368,NaN,20.384728,718.656125,5.956368,8.766792e+06,2.446308e+07
std,3.794427e+05,4.609916,1.754741,NaN,68.610033,2080.198316,1.754741,2.912450e+07,1.116977e+08
min,1.890000e+02,2010.000000,0.000000,NaN,3.860000,0.000000,0.000000,0.000000e+00,0.000000e+00
25%,2.257258e+05,2013.750000,5.600000,NaN,7.840750,53.000000,5.600000,0.000000e+00,0.000000e+00
50%,4.468170e+05,2017.500000,6.300000,NaN,10.913500,138.000000,6.300000,0.000000e+00,0.000000e+00
75%,7.739808e+05,2021.250000,6.923000,NaN,17.336500,422.000000,6.923000,2.200000e+06,1.654473e+06
max,1.440471e+06,2025.000000,10.000000,NaN,3876.006000,37119.000000,10.000000,4.600000e+08,2.799439e+09

In [108]:
df.isnull().sum()

show_id             0
type                0
title               0
director          132
cast              204
country           466
date_added          0
release_year        0
rating              0
duration        16000
genres            107
language            0
description       132
popularity          0
vote_count          0
vote_average        0
budget              0
revenue             0
dtype: int64

In [109]:
df = df.drop(['duration'], axis=1)

In [110]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'genres', 'language', 'description',
       'popularity', 'vote_count', 'vote_average', 'budget', 'revenue'],
      dtype='str')

In [111]:
# Dropping all the rows which have the NaN values (Columns with names or alphabetical stuffs).
df = df.dropna(subset=['director', 'cast', 'country', 'description', 'genres'])

In [112]:
# Finally check full data if any of the Null valueed rows left.
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
genres          0
language        0
description     0
popularity      0
vote_count      0
vote_average    0
budget          0
revenue         0
dtype: int64

In [113]:
df['date_added'] = pd.to_datetime(df['date_added'])

In [114]:
df['genres'].unique()

<StringArray>
[      'Comedy, Adventure, Fantasy, Animation, Family',
                  'Action, Science Fiction, Adventure',
                                  'Adventure, Fantasy',
                        'Animation, Family, Adventure',
               'Fantasy, Adventure, Animation, Family',
                            'Drama, Thriller, Mystery',
                    'Action, Adventure, Drama, Family',
                  'Adventure, Action, Science Fiction',
                                              'Comedy',
                                      'Drama, Romance',
 ...
                  'Animation, Science Fiction, Comedy',
        'Adventure, Fantasy, Thriller, Drama, History',
                                 'Horror, Documentary',
                            'Science Fiction, Romance',
 'Action, Adventure, Science Fiction, Fantasy, Horror',
                                     'Music, Thriller',
  'Science Fiction, Fantasy, Action, Crime, Adventure',
                  'Animation, Romance, Drama, History',
           'Action, Thriller, Romance, Fantasy, Drama',
                    'Drama, Thriller, Mystery, Horror']
Length: 2727, dtype: str

In [115]:
languages = {i: task for i, task in enumerate((df['language'].unique()), start=1)}
languages

{1: 'en',
 2: 'es',
 3: 'sr',
 4: 'pt',
 5: 'ko',
 6: 'fr',
 7: 'hi',
 8: 'ja',
 9: 'th',
 10: 'no',
 11: 'de',
 12: 'zh',
 13: 'it',
 14: 'fi',
 15: 'cn',
 16: 'sv',
 17: 'is',
 18: 'ta',
 19: 'nl',
 20: 'da',
 21: 'ru',
 22: 'tr',
 23: 'el',
 24: 'te',
 25: 'bn',
 26: 'ar',
 27: 'ca',
 28: 'fa',
 29: 'ro',
 30: 'he',
 31: 'cs',
 32: 'hu',
 33: 'pl',
 34: 'ml',
 35: 'ms',
 36: 'id',
 37: 'ku',
 38: 'xx',
 39: 'tl',
 40: 'gl',
 41: 'lt',
 42: 'si',
 43: 'et',
 44: 'hr',
 45: 'mi',
 46: 'uk',
 47: 'af',
 48: 'km',
 49: 'mr',
 50: 'sk',
 51: 'kn',
 52: 'eu',
 53: 'lv',
 54: 'la',
 55: 'dz',
 56: 'kk',
 57: 'mk',
 58: 'ka',
 59: 'vi',
 60: 'mn',
 61: 'pa',
 62: 'ga',
 63: 'yo',
 64: 'zu',
 65: 'ur',
 66: 'am',
 67: 'ne',
 68: 'ky',
 69: 'sl'}

In [116]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['language'] = le.fit_transform(df['language'])
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,"Comedy, Adventure, Fantasy, Animation, Family",11,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,"Action, Science Fiction, Adventure",11,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,"Adventure, Fantasy",11,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,"Animation, Family, Adventure",11,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,"Fantasy, Adventure, Animation, Family",11,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15989,616846,Movie,Psykopat,"Matthew Hart, Renaldo Samsara","Arifin Putra, Cornelio Sunny, Nana Mirdad, Mar...","Indonesia, United Kingdom, United States of Am...",2025-02-06,2025,3.000,"Drama, Thriller, Mystery, Horror",24,A famous illusionist challenges four participa...,4.955,1,3.000,0,0
15990,1424086,Movie,Blood and Stuffing,Ray Brown,"Hariclia Grammenou, Bethany Tickle, Ren, Ray B...",United Kingdom,2025-02-26,2025,0.000,Horror,11,A young girl plays a violent game after her si...,4.953,0,0.000,0,0
15991,1214052,Movie,To a Land Unknown,Mahdi Fleifel,"Mahmood Bakri, Aram Sabbah, Angeliki Papoulia,...","Germany, Saudi Arabia, Qatar, France, Greece, ...",2025-02-14,2025,6.500,"Drama, Thriller, Crime",2,The stakes couldn't be higher for displaced Pa...,4.946,2,6.500,0,0
15996,1271724,Movie,Man and Woman,Vladimir Kott,"Anna Kotova, Stepan Devonin, Pavel Derevyanko,...",Russia,2025-03-13,2025,0.000,Drama,51,Poignant stories about men and women who have ...,4.930,0,0.000,0,0
15999,1405742,Movie,Portal to Hell,Woody Bess,"Trey Holland, Keith David, Richard Kind, Micha...",United States of America,2025-02-22,2025,0.000,"Comedy, Horror",11,After a debt-collector finds a portal to hell ...,4.921,0,0.000,0,0

In [117]:
df.info()

<class 'pandas.DataFrame'>
Index: 15239 entries, 0 to 15999
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       15239 non-null  int64
 1   type          15239 non-null  str
 2   title         15239 non-null  str
 3   director      15239 non-null  str
 4   cast          15239 non-null  str
 5   country       15239 non-null  str
 6   date_added    15239 non-null  datetime64[us]
 7   release_year  15239 non-null  int64
 8   rating        15239 non-null  float64
 9   genres        15239 non-null  str
 10  language      15239 non-null  int64
 11  description   15239 non-null  str
 12  popularity    15239 non-null  float64
 13  vote_count    15239 non-null  int64
 14  vote_average  15239 non-null  float64
 15  budget        15239 non-null  int64
 16  revenue       15239 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(6), str(7)
memory usage: 2.1 MB

In [118]:
# df.to_csv("/workspaces/EDA-on-Netflix-Dataset/datasets/processed/netflix_movies_processed.csv")